### ISSUE TITLE
Dynamic / cache-able Load, own icons

### ISSUE THREAD

**Issue by MentalGear** [antfu/purge-icons#13]
Looks mighty interesting, yet I'm wondering:
1. Does it also allow to dynamically pull icons, so they can be cacheable (for icons that are used across many pages)
2. Can one only use the icon libraries provided, or also own svgs ?

**Comment by antfu** [comment]
1. In that case, I think you can use Iconify directly, it will pull icons from their server and cache them in the localStorage.
2. Yes, it's possible. See https://docs.iconify.design/sources/bundles/
