### ISSUE TITLE
iconify-inline not working

### ISSUE THREAD

**Issue by cyber-carlos** [antfu/purge-icons#15]
iconify's documentation

```html
<p>
   Block:
   <span class="iconify" data-icon="line-md:image-twotone"></span>
   <span class="iconify" data-icon="mdi:account-box-outline"></span>
</p>
<p>
   Inline:
   <span class="iconify-inline" data-icon="line-md:image-twotone"></span>
   <span class="iconify-inline" data-icon="mdi:account-box-outline"></span>
</p>
```

vite-plugin-pruge-icons
```html
<!-- its worked -->
<span class="iconify" :data-icon="iconName" :data-height="size" />

<!-- its not -->
<span class="iconify-inline" :data-icon="iconName" :data-height="size" />
```

**Comment by antfu** [comment]
https://docs.iconify.design/implementations/iconify1/inline-vs-block.html

```html
  <span class="iconify" data-icon="mdi:home" data-inline="true"></span>
```

**Comment by cyber-carlos** [comment]
```html
        <span><span class="iconify" data-icon="mdi:home" data-inline="true"></span>one</span>
        <span><span class="iconify" data-icon="mdi:home" data-inline="false"></span>two</span>
```

![image](https://user-images.githubusercontent.com/50797685/109382312-a9370d00-791a-11eb-8043-1f69e019c0d1.png)

![image](https://user-images.githubusercontent.com/50797685/109382330-ba801980-791a-11eb-87ca-c49c0eb48f0f.png)

I don't know why this happens, what's wrong?
I also used `vite-plugin-windicss` `vite-plugin-components` `vite-plugin-style-import`
Does it matter?

**Comment by antfu** [comment]
windicss might have style reset for SVGs. You can do a check with your inspector. I don't think it's a bug of this project, as all it does is bundling icons you used.

**Comment by cyber-carlos** [comment]
Okay, thank u, I found the reason, WindiCSS reset `img,svg{display:block}`.
