### ISSUE TITLE
Local use

### ISSUE THREAD

**Issue by anncwb** [antfu/purge-icons#16]
Is there a way to use it in an environment that cannot be connected to the external network?

Because a large part of the system is running inside the local area network, is there any way not to request the online api, but still be able to use the plug-in.

**Comment by anncwb** [comment]
![image](https://user-images.githubusercontent.com/28132598/109521782-a25df500-7ae8-11eb-8ced-fe003360cd2a.png)

**Comment by anncwb** [comment]
My thought is can I change this online url to configure the url for myself

**Comment by antfu** [comment]
Install `@iconify/json` would use the ones from your local

**Comment by anncwb** [comment]
![image](https://user-images.githubusercontent.com/28132598/109525682-be639580-7aec-11eb-90c7-fd18e281bbb1.png)

My dependencies are installed. How can I use it, my environment is vite2

**Comment by anncwb** [comment]
I found that @iconify/json is only installed in the project, but it is not used. My code is written here https://github.com/antfu/purge-icons/issues/4

**Comment by antfu** [comment]
In your code, it seems like you are composing icon ids dynamically, which is not detectable from static analysis, see https://github.com/antfu/purge-icons#usage.
