### ISSUE TITLE
[purge-icons-webpack-plugin] TypeError: PurgeIconsPlugin is not a constructor

### ISSUE THREAD

**Issue by ycs77** [antfu/purge-icons#2]
I use purge-icons-webpack-plugin, but  throw `TypeError: PurgeIconsPlugin is not a constructor` error:

```js
const PurgeIconsPlugin = require('purge-icons-webpack-plugin')

module.exports = {
  // ...options
  plugins: [
    new PurgeIconsPlugin({
      /* PurgeIcons Options */
    })
  ]
}
```

Later I changed this code to run:

```js
const PurgeIconsPlugin = require('purge-icons-webpack-plugin').default

// ...
```

**Comment by antfu** [comment]
I think this is a limitation for rollup when outputting in CJS. I don't see a proper way to solve this for now, if anyone knowing more context, please leave comments or just file a PR. Much appreciated.

One other way is to use TypeScript along with Webpack, if TS works for you. https://webpack.js.org/guides/typescript/. With `"esModuleInterop": true` set, it should work as you expected.

**Comment by anish2690** [comment]
@ycs77 for me after switching to 
```ts
const PurgeIconsPlugin = require('purge-icons-webpack-plugin').default
```
`TypeError: Cannot read property 'data' of undefined`

my setup is using "webpack": "^5.0.0-beta.29" with vue-loader

**Comment by anish2690** [comment]
@antfu `"esModuleInterop": true` didn't help for me

**Comment by antfu** [comment]
Guys, what do you think if we change the API to:

```ts
const { PurgeIcons } = require('purge-icons-webpack-plugin')
// or
import { PurgeIcons } from 'purge-icons-webpack-plugin'
```

**Comment by antfu** [comment]
Added in `v0.4.1`. It's backward compatible, so the existing `.default` should also work.

**Comment by ycs77** [comment]
Great!
