### ISSUE TITLE
[Feature request] Vue component plugin

### ISSUE THREAD

**Issue by ycs77** [antfu/purge-icons#4]

**Comment by antfu** [comment]
Can you provide some details about your request?

**Comment by ycs77** [comment]
The problem I have now is when I use `v-model` to change icon, it will not working:

```html
<span class="iconify" :data-icon="show ? 'heroicons-outline:check-circle' : 'heroicons-outline:x-circle'"></span>

<input type="checkbox" v-model="show">
```

It seems that the reason for iconify makes Vue unable to work. May I use the following component to wrap `<span class="iconify" data-icon="..."></span>`? Or is there a better solution?

```html
<Icon :icon="show ? 'heroicons-outline:check-circle' : 'heroicons-outline:x-circle'" />
```

**Comment by antfu** [comment]
https://www.github.com/antfu/vitesse/tree/master/src%2Fcomponents%2FIcon.vue

check out this.

**Comment by ycs77** [comment]
Thanks
