### ISSUE TITLE
Missing plugin.js in nuxt-purge-icons-module

### ISSUE THREAD

**Issue by hannoeru** [antfu/purge-icons#6]
Hi, after I downloaded nuxt-purge-icons-module package, I can't find plugin.js in package folder.

**Comment by antfu** [comment]
Is that a common practice for nuxt plugins to provide a preconfigured plugin.js? 

Before that, you can see https://github.com/antfu/purge-icons/tree/main/examples/nuxt as an example

**Comment by hannoeru** [comment]
Yes it is, you did provide a plugin.js in nuxt-purge-icons-module too.
But l think lerna didn't publish plugin.js to npm.
Example will work is because it use workspace package.

**Comment by antfu** [comment]
Fixed in 0.4.3. Thanks.
