### ISSUE TITLE
[nuxt] renderSVG is not a function in Icon Component

### ISSUE THREAD

**Issue by regenrek** [antfu/purge-icons#7]
Hi

I've noticed there is a problem with the `Icon` component which is used in nuxt. I'm not sure if its 
a problem with webpack loader or default export in `@purge-icons/generated` 

```
Uncaught (in promise) TypeError: _purge_icons_generated__WEBPACK_IMPORTED_MODULE_2___default.a.renderSVG is not a function
```

It works when I changed this
```
import Iconify from '@purge-icons/generated'
```
to this
```
import Iconify from '@iconify/iconify
```

Regards

**Comment by antfu** [comment]
Can't reproduce...

Can you share a minimal reproduce repo? Thanks.

**Comment by antfu** [comment]
Close for inactive. Feel free to reopen if it still presists.
