### ISSUE TITLE
v-show and v-if aren't working properly on icons

### ISSUE THREAD

**Issue by DeFUCC** [antfu/purge-icons#8]
Seems like the replacing of the <span> tags with svg leads to v-show and v-if directives not working. It just renders once and then isn't reactive to the changes. 
Even 
`      <span
        class="iconify"
        :data-icon="myRate.star ? 'la:star-solid' : 'la:star'"
        data-inline="false"
      ></span>` isn't reactive...

**Comment by DeFUCC** [comment]
Only such a construct worked for me:

`     <span v-show="!myRate.star">
        <span class="iconify" data-icon="la:star" data-inline="false"></span>
      </span>
      <span v-show="!!myRate.star">
        <span
          class="iconify"
          data-icon="la:star-solid"
          data-inline="false"
        ></span>
      </span>`

Looks not very clean...

**Comment by antfu** [comment]
This is a limitation of Iconify's usage. I am using this component wrapping the logic https://github.com/antfu/vitesse/blob/master/src/components/Icon.vue

**Comment by DeFUCC** [comment]
I see. Started building a wrapper for my switching purpose. )
