### ISSUE TITLE
vite2.0 Support

### ISSUE THREAD

**Issue by anncwb** [antfu/purge-icons#9]
@antfu  When can vite-plugin-purge-icons adapt to vite2.0? I think `vite-plugin-icons` has been adapted, but I need to use this plugin instead of `vite-plugin-icons`. Because it supports rendering icons in string format. Or can `vite-plugin-icons` also support string rendering icons?

**Comment by antfu** [comment]
Supported in v0.5.0. 

> Can `vite-plugin-icons` also support string rendering icons?

Probably no, I think this is a pro also a con compare to PurgeIcons in different aspects (that's why we are having two different plugins, but I think you can also use them together)
